Added mad check in autotools Updated player controls

diff --git a/beatforce/configure b/beatforce/configure
--- a/beatforce/configure
+++ b/beatforce/configure
@@ -5849,45 +5849,32 @@ else
 fi
 done
 
-for ac_hdr in sys/asoundlib.h
+# AC_CHECK_HEADERS(sys/asoundlib.h)
+
+
+echo $ac_n "checking for libmad files""... $ac_c" 1>&6
+echo "configure:5857: checking for libmad files" >&5
+dir=""
+maddir=""
+for i in $dir /usr /usr/local
 do
-ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
-echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:5857: checking for $ac_hdr" >&5
-if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  cat > conftest.$ac_ext <<EOF
-#line 5862 "configure"
-#include "confdefs.h"
-#include <$ac_hdr>
-EOF
-ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:5867: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
-ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
-if test -z "$ac_err"; then
-  rm -rf conftest*
-  eval "ac_cv_header_$ac_safe=yes"
-else
-  echo "$ac_err" >&5
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_header_$ac_safe=no"
-fi
-rm -f conftest*
-fi
-if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
-  cat >> confdefs.h <<EOF
-#define $ac_tr_hdr 1
-EOF
- 
-else
-  echo "$ac_t""no" 1>&6
-fi
+  if test -f $i/lib/libmad.a && test -f $i/include/mad.h;
+  then
+    echo "$ac_t""mad libs: $i" 1>&6
+    maddir=$i
+    break
+  fi
 done
+
+if test x$maddir = x
+then
+ enable_mp3=no
+ echo "configure: warning: Mad libs not found... disabling mp3 support" 1>&2
+else
+ MADDIR=${maddir}
+ LIBS="$LIBS -lmad -L$MADDIR/lib"
+ CFLAGS="$CFLAGS -I$MADDIR/include -DHAVE_MP3"
+fi
 
 
 #set correct directory
